/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyWinner = IDL.Record({
  'user' : IDL.Principal,
  'amount' : IDL.Int,
});
export const GameResult = IDL.Variant({ 'win' : IDL.Null, 'lose' : IDL.Null });
export const Time = IDL.Int;
export const GameType = IDL.Variant({
  'blackjack' : IDL.Null,
  'dice' : IDL.Null,
  'baccarat' : IDL.Null,
  'slots' : IDL.Null,
  'videoPoker' : IDL.Null,
  'roulette' : IDL.Null,
});
export const UserGame = IDL.Record({
  'bet' : IDL.Nat,
  'result' : GameResult,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'gameType' : GameType,
  'balanceChange' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyCredits' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyWinners' : IDL.Func([], [IDL.Vec(DailyWinner)], ['query']),
  'getGameHistory' : IDL.Func([IDL.Principal], [IDL.Vec(UserGame)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
  'initializeBalance' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'playGame' : IDL.Func([GameType, IDL.Nat], [UserGame], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyWinner = IDL.Record({
    'user' : IDL.Principal,
    'amount' : IDL.Int,
  });
  const GameResult = IDL.Variant({ 'win' : IDL.Null, 'lose' : IDL.Null });
  const Time = IDL.Int;
  const GameType = IDL.Variant({
    'blackjack' : IDL.Null,
    'dice' : IDL.Null,
    'baccarat' : IDL.Null,
    'slots' : IDL.Null,
    'videoPoker' : IDL.Null,
    'roulette' : IDL.Null,
  });
  const UserGame = IDL.Record({
    'bet' : IDL.Nat,
    'result' : GameResult,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'gameType' : GameType,
    'balanceChange' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyCredits' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyWinners' : IDL.Func([], [IDL.Vec(DailyWinner)], ['query']),
    'getGameHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserGame)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
    'initializeBalance' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'playGame' : IDL.Func([GameType, IDL.Nat], [UserGame], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };