/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyWinner { 'user' : Principal, 'amount' : bigint }
export type GameResult = { 'win' : null } |
  { 'lose' : null };
export type GameType = { 'war' : null } |
  { 'mines' : null } |
  { 'penaltyShootout' : null } |
  { 'blackjack' : null } |
  { 'ballDrop' : null } |
  { 'plinko' : null } |
  { 'dice' : null } |
  { 'threeCardPoker' : null } |
  { 'hiLo' : null } |
  { 'keno' : null } |
  { 'craps' : null } |
  { 'wheelOfFortune' : null } |
  { 'scratchCards' : null } |
  { 'limbo' : null } |
  { 'sicBo' : null } |
  { 'baccarat' : null } |
  { 'slots' : null } |
  { 'caribbeanStud' : null } |
  { 'paiGowPoker' : null } |
  { 'letItRide' : null } |
  { 'videoPoker' : null } |
  { 'roulette' : null } |
  { 'casinoHoldem' : null } |
  { 'coinPusher' : null } |
  { 'crashGame' : null };
export type Time = bigint;
export interface UserGame {
  'bet' : bigint,
  'result' : GameResult,
  'user' : Principal,
  'timestamp' : Time,
  'gameType' : GameType,
  'balanceChange' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCredits' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyCredits' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyWinners' : ActorMethod<[], Array<DailyWinner>>,
  'getGameHistory' : ActorMethod<[Principal], Array<UserGame>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'initializeBalance' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'playGame' : ActorMethod<[GameType, bigint], UserGame>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];