/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyWinner { 'user' : Principal, 'amount' : bigint }
export interface FriendInfo { 'principal' : Principal, 'username' : string }
export interface GameChallenge {
  'id' : string,
  'to' : Principal,
  'bet' : bigint,
  'status' : string,
  'from' : Principal,
  'timestamp' : Time,
  'gameType' : GameType,
}
export type GameResult = { 'win' : null } |
  { 'lose' : null };
export interface GameSettings {
  'minBet' : bigint,
  'winMultiplier' : number,
  'maxBet' : bigint,
}
export type GameType = { 'war' : null } |
  { 'mines' : null } |
  { 'penaltyShootout' : null } |
  { 'blackjack' : null } |
  { 'spaceShooter' : null } |
  { 'ballDrop' : null } |
  { 'plinko' : null } |
  { 'whackAMole' : null } |
  { 'dice' : null } |
  { 'threeCardPoker' : null } |
  { 'hiLo' : null } |
  { 'keno' : null } |
  { 'craps' : null } |
  { 'wheelOfFortune' : null } |
  { 'scratchCards' : null } |
  { 'limbo' : null } |
  { 'sicBo' : null } |
  { 'baccarat' : null } |
  { 'slots' : null } |
  { 'snake' : null } |
  { 'caribbeanStud' : null } |
  { 'paiGowPoker' : null } |
  { 'letItRide' : null } |
  { 'videoPoker' : null } |
  { 'roulette' : null } |
  { 'casinoHoldem' : null } |
  { 'coinPusher' : null } |
  { 'crashGame' : null } |
  { 'breakout' : null } |
  { 'pacmanStyle' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'pointPrice' : bigint,
  'category' : string,
}
export interface RedemptionRequest {
  'id' : string,
  'status' : string,
  'userName' : string,
  'user' : Principal,
  'productId' : string,
  'productName' : string,
  'timestamp' : Time,
  'pointPrice' : bigint,
}
export type Time = bigint;
export interface UserGame {
  'bet' : bigint,
  'result' : GameResult,
  'user' : Principal,
  'timestamp' : Time,
  'gameType' : GameType,
  'balanceChange' : bigint,
}
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'username' : string,
  'balance' : bigint,
  'joinDate' : Time,
  'name' : string,
  'role' : string,
  'totalGamesPlayed' : bigint,
  'totalCreditsWon' : bigint,
  'points' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCredits' : ActorMethod<[Principal, bigint], undefined>,
  'addCreditsByUsername' : ActorMethod<[string, bigint], undefined>,
  'addProduct' : ActorMethod<[string, string, string, bigint], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canClaimDailyCredits' : ActorMethod<[], boolean>,
  'cancelGameChallenge' : ActorMethod<[string], GameChallenge>,
  'claimDailyCredits' : ActorMethod<[], undefined>,
  'getAllGameSettings' : ActorMethod<[], Array<[string, GameSettings]>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsAdmin' : ActorMethod<[], Array<Product>>,
  'getAllRedemptions' : ActorMethod<[], Array<RedemptionRequest>>,
  'getAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyWinners' : ActorMethod<[], Array<DailyWinner>>,
  'getFriendRequests' : ActorMethod<
    [],
    Array<{ 'from' : Principal, 'timestamp' : Time, 'fromUsername' : string }>
  >,
  'getFriends' : ActorMethod<[], Array<FriendInfo>>,
  'getGameHistory' : ActorMethod<[Principal], Array<UserGame>>,
  'getGameSettings' : ActorMethod<[GameType], [] | [GameSettings]>,
  'getMyRedemptions' : ActorMethod<[], Array<RedemptionRequest>>,
  'getPendingChallenges' : ActorMethod<[], Array<GameChallenge>>,
  'getPointsBalance' : ActorMethod<[], bigint>,
  'getSentChallenges' : ActorMethod<[], Array<GameChallenge>>,
  'getUserByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsernameByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'initializeBalance' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'playGame' : ActorMethod<[GameType, bigint], UserGame>,
  'recordGameOutcome' : ActorMethod<
    [GameType, bigint, boolean, bigint],
    UserGame
  >,
  'redeemProduct' : ActorMethod<[string], RedemptionRequest>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'removeProduct' : ActorMethod<[string], undefined>,
  'respondFriendRequest' : ActorMethod<[Principal, boolean], undefined>,
  'respondGameChallenge' : ActorMethod<[string, boolean], GameChallenge>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[string], undefined>,
  'sendGameChallenge' : ActorMethod<[string, GameType, bigint], GameChallenge>,
  'setGameSettings' : ActorMethod<[GameType, GameSettings], undefined>,
  'setUsername' : ActorMethod<[string], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, string, bigint, boolean],
    Product
  >,
  'updateRedemptionStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];