/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'pointPrice' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const GameType = IDL.Variant({
  'war' : IDL.Null,
  'mines' : IDL.Null,
  'penaltyShootout' : IDL.Null,
  'blackjack' : IDL.Null,
  'spaceShooter' : IDL.Null,
  'ballDrop' : IDL.Null,
  'plinko' : IDL.Null,
  'whackAMole' : IDL.Null,
  'dice' : IDL.Null,
  'threeCardPoker' : IDL.Null,
  'hiLo' : IDL.Null,
  'keno' : IDL.Null,
  'craps' : IDL.Null,
  'wheelOfFortune' : IDL.Null,
  'scratchCards' : IDL.Null,
  'limbo' : IDL.Null,
  'sicBo' : IDL.Null,
  'baccarat' : IDL.Null,
  'slots' : IDL.Null,
  'snake' : IDL.Null,
  'caribbeanStud' : IDL.Null,
  'paiGowPoker' : IDL.Null,
  'letItRide' : IDL.Null,
  'videoPoker' : IDL.Null,
  'roulette' : IDL.Null,
  'casinoHoldem' : IDL.Null,
  'coinPusher' : IDL.Null,
  'crashGame' : IDL.Null,
  'breakout' : IDL.Null,
  'pacmanStyle' : IDL.Null,
});
export const GameChallenge = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'bet' : IDL.Nat,
  'status' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : Time,
  'gameType' : GameType,
});
export const GameSettings = IDL.Record({
  'minBet' : IDL.Nat,
  'winMultiplier' : IDL.Float64,
  'maxBet' : IDL.Nat,
});
export const RedemptionRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userName' : IDL.Text,
  'user' : IDL.Principal,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'timestamp' : Time,
  'pointPrice' : IDL.Nat,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'balance' : IDL.Int,
  'joinDate' : Time,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'totalGamesPlayed' : IDL.Nat,
  'totalCreditsWon' : IDL.Int,
  'points' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const DailyWinner = IDL.Record({
  'user' : IDL.Principal,
  'amount' : IDL.Int,
});
export const FriendInfo = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
});
export const GameResult = IDL.Variant({ 'win' : IDL.Null, 'lose' : IDL.Null });
export const UserGame = IDL.Record({
  'bet' : IDL.Nat,
  'result' : GameResult,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'gameType' : GameType,
  'balanceChange' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'addCreditsByUsername' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Product],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canClaimDailyCredits' : IDL.Func([], [IDL.Bool], ['query']),
  'cancelGameChallenge' : IDL.Func([IDL.Text], [GameChallenge], []),
  'claimDailyCredits' : IDL.Func([], [], []),
  'getAllGameSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, GameSettings))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllRedemptions' : IDL.Func([], [IDL.Vec(RedemptionRequest)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyWinners' : IDL.Func([], [IDL.Vec(DailyWinner)], ['query']),
  'getFriendRequests' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'from' : IDL.Principal,
            'timestamp' : Time,
            'fromUsername' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getFriends' : IDL.Func([], [IDL.Vec(FriendInfo)], ['query']),
  'getGameHistory' : IDL.Func([IDL.Principal], [IDL.Vec(UserGame)], ['query']),
  'getGameSettings' : IDL.Func([GameType], [IDL.Opt(GameSettings)], ['query']),
  'getMyRedemptions' : IDL.Func([], [IDL.Vec(RedemptionRequest)], ['query']),
  'getPendingChallenges' : IDL.Func([], [IDL.Vec(GameChallenge)], ['query']),
  'getPointsBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getSentChallenges' : IDL.Func([], [IDL.Vec(GameChallenge)], ['query']),
  'getUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsernameByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
  'initializeBalance' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'playGame' : IDL.Func([GameType, IDL.Nat], [UserGame], []),
  'recordGameOutcome' : IDL.Func(
      [GameType, IDL.Nat, IDL.Bool, IDL.Nat],
      [UserGame],
      [],
    ),
  'redeemProduct' : IDL.Func([IDL.Text], [RedemptionRequest], []),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'respondFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'respondGameChallenge' : IDL.Func([IDL.Text, IDL.Bool], [GameChallenge], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Text], [], []),
  'sendGameChallenge' : IDL.Func(
      [IDL.Text, GameType, IDL.Nat],
      [GameChallenge],
      [],
    ),
  'setGameSettings' : IDL.Func([GameType, GameSettings], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [Product],
      [],
    ),
  'updateRedemptionStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'pointPrice' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const GameType = IDL.Variant({
    'war' : IDL.Null,
    'mines' : IDL.Null,
    'penaltyShootout' : IDL.Null,
    'blackjack' : IDL.Null,
    'spaceShooter' : IDL.Null,
    'ballDrop' : IDL.Null,
    'plinko' : IDL.Null,
    'whackAMole' : IDL.Null,
    'dice' : IDL.Null,
    'threeCardPoker' : IDL.Null,
    'hiLo' : IDL.Null,
    'keno' : IDL.Null,
    'craps' : IDL.Null,
    'wheelOfFortune' : IDL.Null,
    'scratchCards' : IDL.Null,
    'limbo' : IDL.Null,
    'sicBo' : IDL.Null,
    'baccarat' : IDL.Null,
    'slots' : IDL.Null,
    'snake' : IDL.Null,
    'caribbeanStud' : IDL.Null,
    'paiGowPoker' : IDL.Null,
    'letItRide' : IDL.Null,
    'videoPoker' : IDL.Null,
    'roulette' : IDL.Null,
    'casinoHoldem' : IDL.Null,
    'coinPusher' : IDL.Null,
    'crashGame' : IDL.Null,
    'breakout' : IDL.Null,
    'pacmanStyle' : IDL.Null,
  });
  const GameChallenge = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'bet' : IDL.Nat,
    'status' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : Time,
    'gameType' : GameType,
  });
  const GameSettings = IDL.Record({
    'minBet' : IDL.Nat,
    'winMultiplier' : IDL.Float64,
    'maxBet' : IDL.Nat,
  });
  const RedemptionRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userName' : IDL.Text,
    'user' : IDL.Principal,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'timestamp' : Time,
    'pointPrice' : IDL.Nat,
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'balance' : IDL.Int,
    'joinDate' : Time,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'totalGamesPlayed' : IDL.Nat,
    'totalCreditsWon' : IDL.Int,
    'points' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const DailyWinner = IDL.Record({
    'user' : IDL.Principal,
    'amount' : IDL.Int,
  });
  const FriendInfo = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
  });
  const GameResult = IDL.Variant({ 'win' : IDL.Null, 'lose' : IDL.Null });
  const UserGame = IDL.Record({
    'bet' : IDL.Nat,
    'result' : GameResult,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'gameType' : GameType,
    'balanceChange' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'addCreditsByUsername' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Product],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canClaimDailyCredits' : IDL.Func([], [IDL.Bool], ['query']),
    'cancelGameChallenge' : IDL.Func([IDL.Text], [GameChallenge], []),
    'claimDailyCredits' : IDL.Func([], [], []),
    'getAllGameSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, GameSettings))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllRedemptions' : IDL.Func([], [IDL.Vec(RedemptionRequest)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyWinners' : IDL.Func([], [IDL.Vec(DailyWinner)], ['query']),
    'getFriendRequests' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'from' : IDL.Principal,
              'timestamp' : Time,
              'fromUsername' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getFriends' : IDL.Func([], [IDL.Vec(FriendInfo)], ['query']),
    'getGameHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserGame)],
        ['query'],
      ),
    'getGameSettings' : IDL.Func(
        [GameType],
        [IDL.Opt(GameSettings)],
        ['query'],
      ),
    'getMyRedemptions' : IDL.Func([], [IDL.Vec(RedemptionRequest)], ['query']),
    'getPendingChallenges' : IDL.Func([], [IDL.Vec(GameChallenge)], ['query']),
    'getPointsBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getSentChallenges' : IDL.Func([], [IDL.Vec(GameChallenge)], ['query']),
    'getUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsernameByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
    'initializeBalance' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'playGame' : IDL.Func([GameType, IDL.Nat], [UserGame], []),
    'recordGameOutcome' : IDL.Func(
        [GameType, IDL.Nat, IDL.Bool, IDL.Nat],
        [UserGame],
        [],
      ),
    'redeemProduct' : IDL.Func([IDL.Text], [RedemptionRequest], []),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'respondFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'respondGameChallenge' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [GameChallenge],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Text], [], []),
    'sendGameChallenge' : IDL.Func(
        [IDL.Text, GameType, IDL.Nat],
        [GameChallenge],
        [],
      ),
    'setGameSettings' : IDL.Func([GameType, GameSettings], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [Product],
        [],
      ),
    'updateRedemptionStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };