/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GameChallenge {
    id: string;
    to: Principal;
    bet: bigint;
    status: string;
    from: Principal;
    timestamp: Time;
    gameType: GameType;
}
export interface GameSettings {
    minBet: bigint;
    winMultiplier: number;
    maxBet: bigint;
}
export type Time = bigint;
export interface FriendInfo {
    principal: Principal;
    username: string;
}
export interface DailyWinner {
    user: Principal;
    amount: bigint;
}
export interface UserGame {
    bet: bigint;
    result: GameResult;
    user: Principal;
    timestamp: Time;
    gameType: GameType;
    balanceChange: bigint;
}
export interface RedemptionRequest {
    id: string;
    status: string;
    userName: string;
    user: Principal;
    productId: string;
    productName: string;
    timestamp: Time;
    pointPrice: bigint;
}
export interface UserSummary {
    principal: Principal;
    username: string;
    balance: bigint;
    joinDate: Time;
    name: string;
    role: string;
    totalGamesPlayed: bigint;
    totalCreditsWon: bigint;
    points: bigint;
}
export interface Product {
    id: string;
    name: string;
    description: string;
    available: boolean;
    pointPrice: bigint;
    category: string;
}
export interface UserProfile {
    username: string;
    name: string;
}
export enum GameResult {
    win = "win",
    lose = "lose"
}
export enum GameType {
    war = "war",
    mines = "mines",
    penaltyShootout = "penaltyShootout",
    blackjack = "blackjack",
    spaceShooter = "spaceShooter",
    ballDrop = "ballDrop",
    plinko = "plinko",
    whackAMole = "whackAMole",
    dice = "dice",
    threeCardPoker = "threeCardPoker",
    hiLo = "hiLo",
    keno = "keno",
    craps = "craps",
    wheelOfFortune = "wheelOfFortune",
    scratchCards = "scratchCards",
    limbo = "limbo",
    sicBo = "sicBo",
    baccarat = "baccarat",
    slots = "slots",
    snake = "snake",
    caribbeanStud = "caribbeanStud",
    paiGowPoker = "paiGowPoker",
    letItRide = "letItRide",
    videoPoker = "videoPoker",
    roulette = "roulette",
    casinoHoldem = "casinoHoldem",
    coinPusher = "coinPusher",
    crashGame = "crashGame",
    breakout = "breakout",
    pacmanStyle = "pacmanStyle"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCredits(user: Principal, amount: bigint): Promise<void>;
    addCreditsByUsername(username: string, amount: bigint): Promise<void>;
    addProduct(name: string, description: string, category: string, pointPrice: bigint): Promise<Product>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canClaimDailyCredits(): Promise<boolean>;
    cancelGameChallenge(challengeId: string): Promise<GameChallenge>;
    claimDailyCredits(): Promise<void>;
    getAllGameSettings(): Promise<Array<[string, GameSettings]>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllProductsAdmin(): Promise<Array<Product>>;
    getAllRedemptions(): Promise<Array<RedemptionRequest>>;
    getAllUsers(): Promise<Array<UserSummary>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyWinners(): Promise<Array<DailyWinner>>;
    getFriendRequests(): Promise<Array<{
        from: Principal;
        timestamp: Time;
        fromUsername: string;
    }>>;
    getFriends(): Promise<Array<FriendInfo>>;
    getGameHistory(user: Principal): Promise<Array<UserGame>>;
    getGameSettings(gameType: GameType): Promise<GameSettings | null>;
    getMyRedemptions(): Promise<Array<RedemptionRequest>>;
    getPendingChallenges(): Promise<Array<GameChallenge>>;
    getPointsBalance(): Promise<bigint>;
    getSentChallenges(): Promise<Array<GameChallenge>>;
    getUserByUsername(username: string): Promise<Principal | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsernameByPrincipal(user: Principal): Promise<string | null>;
    getWalletBalance(): Promise<bigint>;
    initializeBalance(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    playGame(gameType: GameType, bet: bigint): Promise<UserGame>;
    recordGameOutcome(gameType: GameType, bet: bigint, won: boolean, winAmount: bigint): Promise<UserGame>;
    redeemProduct(productId: string): Promise<RedemptionRequest>;
    removeFriend(friendPrincipal: Principal): Promise<void>;
    removeProduct(id: string): Promise<void>;
    respondFriendRequest(fromPrincipal: Principal, accept: boolean): Promise<void>;
    respondGameChallenge(challengeId: string, accept: boolean): Promise<GameChallenge>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendFriendRequest(toUsername: string): Promise<void>;
    sendGameChallenge(toUsername: string, gameType: GameType, bet: bigint): Promise<GameChallenge>;
    setGameSettings(gameType: GameType, settings: GameSettings): Promise<void>;
    setUsername(username: string): Promise<void>;
    updateProduct(id: string, name: string, description: string, category: string, pointPrice: bigint, available: boolean): Promise<Product>;
    updateRedemptionStatus(id: string, status: string): Promise<void>;
}
import type { GameChallenge as _GameChallenge, GameResult as _GameResult, GameSettings as _GameSettings, GameType as _GameType, Time as _Time, UserGame as _UserGame, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCredits(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredits(arg0, arg1);
            return result;
        }
    }
    async addCreditsByUsername(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCreditsByUsername(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCreditsByUsername(arg0, arg1);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canClaimDailyCredits(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canClaimDailyCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canClaimDailyCredits();
            return result;
        }
    }
    async cancelGameChallenge(arg0: string): Promise<GameChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelGameChallenge(arg0);
                return from_candid_GameChallenge_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelGameChallenge(arg0);
            return from_candid_GameChallenge_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimDailyCredits(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyCredits();
            return result;
        }
    }
    async getAllGameSettings(): Promise<Array<[string, GameSettings]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGameSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGameSettings();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllProductsAdmin(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductsAdmin();
            return result;
        }
    }
    async getAllRedemptions(): Promise<Array<RedemptionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRedemptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRedemptions();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyWinners(): Promise<Array<DailyWinner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyWinners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyWinners();
            return result;
        }
    }
    async getFriendRequests(): Promise<Array<{
        from: Principal;
        timestamp: Time;
        fromUsername: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return result;
        }
    }
    async getFriends(): Promise<Array<FriendInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getGameHistory(arg0: Principal): Promise<Array<UserGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameHistory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameHistory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameSettings(arg0: GameType): Promise<GameSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameSettings(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameSettings(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRedemptions(): Promise<Array<RedemptionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRedemptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRedemptions();
            return result;
        }
    }
    async getPendingChallenges(): Promise<Array<GameChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingChallenges();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingChallenges();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPointsBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointsBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointsBalance();
            return result;
        }
    }
    async getSentChallenges(): Promise<Array<GameChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentChallenges();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentChallenges();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByUsername(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsernameByPrincipal(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsernameByPrincipal(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsernameByPrincipal(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async initializeBalance(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async playGame(arg0: GameType, arg1: bigint): Promise<UserGame> {
        if (this.processError) {
            try {
                const result = await this.actor.playGame(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_UserGame_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.playGame(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_UserGame_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordGameOutcome(arg0: GameType, arg1: bigint, arg2: boolean, arg3: bigint): Promise<UserGame> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGameOutcome(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_UserGame_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGameOutcome(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_UserGame_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemProduct(arg0: string): Promise<RedemptionRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemProduct(arg0);
            return result;
        }
    }
    async removeFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async removeProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProduct(arg0);
            return result;
        }
    }
    async respondFriendRequest(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondFriendRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondFriendRequest(arg0, arg1);
            return result;
        }
    }
    async respondGameChallenge(arg0: string, arg1: boolean): Promise<GameChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.respondGameChallenge(arg0, arg1);
                return from_candid_GameChallenge_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondGameChallenge(arg0, arg1);
            return from_candid_GameChallenge_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendGameChallenge(arg0: string, arg1: GameType, arg2: bigint): Promise<GameChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGameChallenge(arg0, to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_GameChallenge_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGameChallenge(arg0, to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_GameChallenge_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGameSettings(arg0: GameType, arg1: GameSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGameSettings(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGameSettings(to_candid_GameType_n15(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async setUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsername(arg0);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: boolean): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateRedemptionStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRedemptionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRedemptionStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_GameChallenge_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameChallenge): GameChallenge {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GameResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameResult): GameResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserGame_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserGame): UserGame {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameSettings]): GameSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bet: bigint;
    result: _GameResult;
    user: Principal;
    timestamp: _Time;
    gameType: _GameType;
    balanceChange: bigint;
}): {
    bet: bigint;
    result: GameResult;
    user: Principal;
    timestamp: Time;
    gameType: GameType;
    balanceChange: bigint;
} {
    return {
        bet: value.bet,
        result: from_candid_GameResult_n13(_uploadFile, _downloadFile, value.result),
        user: value.user,
        timestamp: value.timestamp,
        gameType: from_candid_GameType_n5(_uploadFile, _downloadFile, value.gameType),
        balanceChange: value.balanceChange
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    to: Principal;
    bet: bigint;
    status: string;
    from: Principal;
    timestamp: _Time;
    gameType: _GameType;
}): {
    id: string;
    to: Principal;
    bet: bigint;
    status: string;
    from: Principal;
    timestamp: Time;
    gameType: GameType;
} {
    return {
        id: value.id,
        to: value.to,
        bet: value.bet,
        status: value.status,
        from: value.from,
        timestamp: value.timestamp,
        gameType: from_candid_GameType_n5(_uploadFile, _downloadFile, value.gameType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    lose: null;
}): GameResult {
    return "win" in value ? GameResult.win : "lose" in value ? GameResult.lose : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    war: null;
} | {
    mines: null;
} | {
    penaltyShootout: null;
} | {
    blackjack: null;
} | {
    spaceShooter: null;
} | {
    ballDrop: null;
} | {
    plinko: null;
} | {
    whackAMole: null;
} | {
    dice: null;
} | {
    threeCardPoker: null;
} | {
    hiLo: null;
} | {
    keno: null;
} | {
    craps: null;
} | {
    wheelOfFortune: null;
} | {
    scratchCards: null;
} | {
    limbo: null;
} | {
    sicBo: null;
} | {
    baccarat: null;
} | {
    slots: null;
} | {
    snake: null;
} | {
    caribbeanStud: null;
} | {
    paiGowPoker: null;
} | {
    letItRide: null;
} | {
    videoPoker: null;
} | {
    roulette: null;
} | {
    casinoHoldem: null;
} | {
    coinPusher: null;
} | {
    crashGame: null;
} | {
    breakout: null;
} | {
    pacmanStyle: null;
}): GameType {
    return "war" in value ? GameType.war : "mines" in value ? GameType.mines : "penaltyShootout" in value ? GameType.penaltyShootout : "blackjack" in value ? GameType.blackjack : "spaceShooter" in value ? GameType.spaceShooter : "ballDrop" in value ? GameType.ballDrop : "plinko" in value ? GameType.plinko : "whackAMole" in value ? GameType.whackAMole : "dice" in value ? GameType.dice : "threeCardPoker" in value ? GameType.threeCardPoker : "hiLo" in value ? GameType.hiLo : "keno" in value ? GameType.keno : "craps" in value ? GameType.craps : "wheelOfFortune" in value ? GameType.wheelOfFortune : "scratchCards" in value ? GameType.scratchCards : "limbo" in value ? GameType.limbo : "sicBo" in value ? GameType.sicBo : "baccarat" in value ? GameType.baccarat : "slots" in value ? GameType.slots : "snake" in value ? GameType.snake : "caribbeanStud" in value ? GameType.caribbeanStud : "paiGowPoker" in value ? GameType.paiGowPoker : "letItRide" in value ? GameType.letItRide : "videoPoker" in value ? GameType.videoPoker : "roulette" in value ? GameType.roulette : "casinoHoldem" in value ? GameType.casinoHoldem : "coinPusher" in value ? GameType.coinPusher : "crashGame" in value ? GameType.crashGame : "breakout" in value ? GameType.breakout : "pacmanStyle" in value ? GameType.pacmanStyle : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserGame>): Array<UserGame> {
    return value.map((x)=>from_candid_UserGame_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameChallenge>): Array<GameChallenge> {
    return value.map((x)=>from_candid_GameChallenge_n3(_uploadFile, _downloadFile, x));
}
function to_candid_GameType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): _GameType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): {
    war: null;
} | {
    mines: null;
} | {
    penaltyShootout: null;
} | {
    blackjack: null;
} | {
    spaceShooter: null;
} | {
    ballDrop: null;
} | {
    plinko: null;
} | {
    whackAMole: null;
} | {
    dice: null;
} | {
    threeCardPoker: null;
} | {
    hiLo: null;
} | {
    keno: null;
} | {
    craps: null;
} | {
    wheelOfFortune: null;
} | {
    scratchCards: null;
} | {
    limbo: null;
} | {
    sicBo: null;
} | {
    baccarat: null;
} | {
    slots: null;
} | {
    snake: null;
} | {
    caribbeanStud: null;
} | {
    paiGowPoker: null;
} | {
    letItRide: null;
} | {
    videoPoker: null;
} | {
    roulette: null;
} | {
    casinoHoldem: null;
} | {
    coinPusher: null;
} | {
    crashGame: null;
} | {
    breakout: null;
} | {
    pacmanStyle: null;
} {
    return value == GameType.war ? {
        war: null
    } : value == GameType.mines ? {
        mines: null
    } : value == GameType.penaltyShootout ? {
        penaltyShootout: null
    } : value == GameType.blackjack ? {
        blackjack: null
    } : value == GameType.spaceShooter ? {
        spaceShooter: null
    } : value == GameType.ballDrop ? {
        ballDrop: null
    } : value == GameType.plinko ? {
        plinko: null
    } : value == GameType.whackAMole ? {
        whackAMole: null
    } : value == GameType.dice ? {
        dice: null
    } : value == GameType.threeCardPoker ? {
        threeCardPoker: null
    } : value == GameType.hiLo ? {
        hiLo: null
    } : value == GameType.keno ? {
        keno: null
    } : value == GameType.craps ? {
        craps: null
    } : value == GameType.wheelOfFortune ? {
        wheelOfFortune: null
    } : value == GameType.scratchCards ? {
        scratchCards: null
    } : value == GameType.limbo ? {
        limbo: null
    } : value == GameType.sicBo ? {
        sicBo: null
    } : value == GameType.baccarat ? {
        baccarat: null
    } : value == GameType.slots ? {
        slots: null
    } : value == GameType.snake ? {
        snake: null
    } : value == GameType.caribbeanStud ? {
        caribbeanStud: null
    } : value == GameType.paiGowPoker ? {
        paiGowPoker: null
    } : value == GameType.letItRide ? {
        letItRide: null
    } : value == GameType.videoPoker ? {
        videoPoker: null
    } : value == GameType.roulette ? {
        roulette: null
    } : value == GameType.casinoHoldem ? {
        casinoHoldem: null
    } : value == GameType.coinPusher ? {
        coinPusher: null
    } : value == GameType.crashGame ? {
        crashGame: null
    } : value == GameType.breakout ? {
        breakout: null
    } : value == GameType.pacmanStyle ? {
        pacmanStyle: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
